[haproxy_api]
bind_ip = "0.0.0.0"   # The IP to bind to for this service
bind_port = 7778      # Port we'll bind to for this service

[haproxy]
bind_ip     = "192.168.168.168"       # Bind IP for HAproxy itself
template    = "templates/haproxy.cfg" # Template to use for HAproxy
config_file = "/etc/haproxy.cfg"      # Where to write the config
pid_file    = "/var/run/haproxy.pid"  # Where to write the HAproxy pid file

[sidecar]
state_url = "http://localhost:7777/state.json" # Where to fetch our initial state
