#!/bin/sh

# stderr -> stdout
exec 2>&1

cd /haproxy-api

if [[ -n "$HAPROXYAPI_LOGGING_LEVEL" ]]; then
    sed -i.bak 's/logging_level *= *"info"/logging_level = "'"$HAPROXYAPI_LOGGING_LEVEL"'"/' haproxy-api.toml
fi

cat /haproxy-api/release-notes.txt
exec ./haproxy-api -f haproxy-api.toml
